services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPassword123.
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
    driver: local