// SolemnVisit Management Constants
export const GET_SOLEMN_VISITS = 'GET_SOLEMN_VISITS';
export const ADD_SOLEMN_VISIT = 'ADD_SOLEMN_VISIT';
export const UPDATE_SOLEMN_VISIT = 'UPDATE_SOLEMN_VISIT';
export const DELETE_SOLEMN_VISIT = 'DELETE_SOLEMN_VISIT';
export const SET_SOLEMN_VISIT_DETAIL = 'SET_SOLEMN_VISIT_DETAIL';
export const SET_SELECTED_SOLEMN_VISITS = 'SET_SELECTED_SOLEMN_VISITS';
export const CLEAR_SELECTED_SOLEMN_VISITS = 'CLEAR_SELECTED_SOLEMN_VISITS';


